---
title: "Gender Pay Gap Analysis"
author: "Group 9"
output: 
  html_document:
    toc: true
    toc_float: TRUE
    theme: paper
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "left", 
                      fig.width = 10)

pacman::p_load(kableExtra, ggrepel, scales, janitor, tidyverse, lubridate)
```

```{r}
pay_data_files <- list.files("../data/", pattern = ".*Pay.*", full.names = T) 

univ_data <- read_csv("../data/universities.csv")

raw_pay_data <- pay_data_files |> 
  set_names() |> 
  map_dfr(read_csv, .id = "yr") |> 
  mutate(yr =gsub(".*([0-9]{4}) to .*([0-9]{2}).*", "\\1-\\2", yr))

df <- inner_join(univ_data, raw_pay_data, by = "EmployerId") |> 
  clean_names() |> 
  select(employer_name = employer_name_x, 
         employer_id, 
         pre92, 
         yr, 
         diff_mean_hourly_percent:female_top_quartile,
         employer_size) 
```


### Table 1. Number of universities submitting data by pre92 status 
```{r totals}
df |> 
  tabyl(yr,pre92) |> 
  adorn_totals(c("row", "col")) |> 
  kable(col.names = c("Year", "No", "Yes", "Total"),
        align = "lccc") |> 
  kable_styling(full_width = FALSE, position="left")
```

### Table 2. Difference in median hourly wage percent
```{r}
df |> 
  group_by(Year = yr) |> 
  summarise(`Mean difference` = mean(diff_median_hourly_percent) %>% 
              round(.,1)%>%
              paste0(., "%")) |> 
  kable(align = "lc") |> 
  kable_styling(full_width = FALSE, position="left")

```

### Table 3. Wage difference by pre92 status and year 
```{r}
df |> 
  group_by(yr, pre92) |> 
  summarise(x = round(mean(diff_median_hourly_percent),1), 
            .groups = "drop") |> 
  mutate(x = paste0(x, "%")) |> 
  pivot_wider(names_from = pre92, values_from = x) |> 
  kable(align = "lcc", 
        col.names = c("Year", "Pre92", "Not Pre92")) |> 
  kable_styling(full_width = FALSE, position="left")
```

### Figure 1. Differences in median hourly wage
```{r fig.asp = 0.8, fig.width = 11, out.width= "100%"}

find_outlier <- function(x) {
  return(x < quantile(x, .25) - 1.5*IQR(x) | x > quantile(x, .75) + 1.5*IQR(x))
}

df |> 
  group_by(yr, pre92) |> 
  mutate(employer_name = toupper(employer_name),
    outlier =ifelse(find_outlier(diff_median_hourly_percent), employer_name, NA)) |> 
  ungroup() |> 
  ggplot(aes(yr,diff_median_hourly_percent,fill = pre92))+
  geom_boxplot() +
  geom_text_repel(aes(label = outlier), na.rm = TRUE, show.legend = F)+
  scale_y_continuous(breaks = seq(0,100, 10), labels = percent_format(scale = 1))+
  theme_classic() +
  labs(x = NULL, 
       y = "Difference in median hourly wage\n", 
       title = "Differences in median hourly wages have not changed much in last five years.\nUniversities established before 1992 have higher median differences compared to those established after 1992.",
       subtitle = "",
       caption = "\nData source: UK Government gender pay gap service", 
       fill = "Universities established before 1992")+
  theme(legend.position = "top", 
        text = element_text(size = 14), 
        plot.title = element_text(size =12))
```

### Figure 2. Differences in proportion of women working by quartile
```{r fig.asp = 0.8, fig.width = 11, out.width= "110%"}
df |> 
  select(pre92, contains("female")) |> 
  select(-female_bonus_percent) |> 
  pivot_longer(-pre92, names_to = "measure") |> 
  mutate(measure = case_when(
    measure == "female_lower_middle_quartile" ~ "Lower middle quartile",
    measure == "female_lower_quartile" ~ "Lower quartile",
    measure == "female_upper_middle_quartile" ~ "Top middle quartile",
    measure == "female_top_quartile" ~ "Top quartile") |> 
      factor(levels = c("Top quartile", 
                        "Top middle quartile",
                        "Lower middle quartile",
                        "Lower quartile"))) |> 
  ggplot()+
  geom_boxplot(aes(x = fct_rev(measure), y = value, fill = pre92)) +
  scale_y_continuous(breaks = seq(0,100, 10), labels = percent_format(scale = 1))+
  geom_hline(aes(yintercept= 50), linetype = "dashed", color = "red")+
  theme_classic() +
  labs(x = NULL, 
       y = "Proportion of women in workforce\n", 
       title = "The proportion of women working in top quartile is lower compared to other quartiles.\nUniversities established before 1992 have lower proportion of women in top quartile compared to those established after 1992.",
       caption = "\nData source: UK Government gender pay gap service",
       fill = "Universities established before 1992") +
  theme(legend.position = "top", 
     text = element_text(size = 14), 
        plot.title = element_text(size =12))
```




